"""Pure Phase 3 unified deterministic scorer, isolated from v1 runtime."""

from backend.app.unified_scoring.models import (
    BehaviorProfileSelection,
    BranchingDimensionsExplanation,
    BranchingPresentation,
    BranchingScenarioExplanation,
    BranchingTimelineExplanation,
    Decimal2,
    Explanation,
    FinancialStateExplanation,
    FormulaExplanation,
    IssuedValueExplanation,
    ObjectiveExplanation,
    RecommendationExplanation,
    StateDeltaExplanation,
    StaticSjtExplanation,
    UnifiedInstrumentPresentation,
    UnifiedScoreResult,
    canonical_fraction_string,
)
from backend.app.unified_scoring.service import (
    BRANCHING_WEAK_SCORE_THRESHOLD,
    LIMITATIONS,
    UnifiedScoringError,
    build_branching_presentations,
    build_unified_presentation,
    legacy_demo_score,
    quantize_fraction_half_up,
    round_fraction_half_up,
    score_assessment,
    score_unified_assessment,
)

__all__ = [
    "BRANCHING_WEAK_SCORE_THRESHOLD",
    "LIMITATIONS",
    "BehaviorProfileSelection",
    "BranchingDimensionsExplanation",
    "BranchingPresentation",
    "BranchingScenarioExplanation",
    "BranchingTimelineExplanation",
    "Decimal2",
    "Explanation",
    "FinancialStateExplanation",
    "FormulaExplanation",
    "IssuedValueExplanation",
    "ObjectiveExplanation",
    "RecommendationExplanation",
    "StateDeltaExplanation",
    "StaticSjtExplanation",
    "UnifiedInstrumentPresentation",
    "UnifiedScoreResult",
    "UnifiedScoringError",
    "build_branching_presentations",
    "build_unified_presentation",
    "canonical_fraction_string",
    "legacy_demo_score",
    "quantize_fraction_half_up",
    "round_fraction_half_up",
    "score_assessment",
    "score_unified_assessment",
]
