"""Pure Phase 2 branching financial-state engine."""

from backend.app.branching.engine import (
    enumerate_paths,
    evaluate_all_paths,
    run_scenario,
    validate_definition,
)
from backend.app.branching.scenarios import build_branching_scenarios
from backend.app.branching.model import (
    STATE_FIELDS,
    BranchingOption,
    BranchingStage,
    CanonicalState,
    FinancialState,
    InvalidScenarioDefinition,
    InvalidState,
    InvalidTransition,
    ScenarioDefinition,
    ScenarioResult,
    State,
    StateDelta,
    TerminalDimensions,
    TransitionEvidence,
    UnknownBranchOption,
    add_late_payment,
    borrow_cash,
    branching_scenario_score,
    normalize_branching_scenario_score,
    clamp01,
    pay_from_buffer,
    pay_from_cash,
    receive_confirmed_inflow,
    terminal_dimensions,
    validate_transition,
)

__all__ = [
    "STATE_FIELDS",
    "BranchingOption",
    "BranchingStage",
    "CanonicalState",
    "FinancialState",
    "InvalidScenarioDefinition",
    "InvalidState",
    "InvalidTransition",
    "ScenarioDefinition",
    "ScenarioResult",
    "State",
    "StateDelta",
    "TerminalDimensions",
    "TransitionEvidence",
    "UnknownBranchOption",
    "add_late_payment",
    "borrow_cash",
    "branching_scenario_score",
    "normalize_branching_scenario_score",
    "build_branching_scenarios",
    "clamp01",
    "enumerate_paths",
    "evaluate_all_paths",
    "pay_from_buffer",
    "pay_from_cash",
    "receive_confirmed_inflow",
    "run_scenario",
    "terminal_dimensions",
    "validate_definition",
    "validate_transition",
]
